benavlabs/fastcrud

- docs/advanced/crud.md
- docs/advanced/endpoint.md
- docs/advanced/overview.md
- docs/usage/crud.md
- fastcrud/crud/fast_crud.py
- fastcrud/endpoint/crud_router.py
- fastcrud/endpoint/endpoint_creator.py
- mkdocs.yml
- pyproject.toml
- tests/sqlalchemy/conftest.py
- tests/sqlalchemy/crud/test_count.py
- tests/sqlalchemy/crud/test_delete.py
- tests/sqlalchemy/crud/test_exists.py
- tests/sqlalchemy/crud/test_get.py
- tests/sqlalchemy/crud/test_get_joined.py
- tests/sqlalchemy/crud/test_get_multi.py
- tests/sqlalchemy/crud/test_get_multi_by_cursor.py
- tests/sqlalchemy/crud/test_get_multi_joined.py
- tests/sqlalchemy/crud/test_update.py
- tests/sqlmodel/conftest.py
- tests/sqlmodel/crud/test_count.py
- tests/sqlmodel/crud/test_delete.py
- tests/sqlmodel/crud/test_exists.py
- tests/sqlmodel/crud/test_get.py
- tests/sqlmodel/crud/test_get_joined.py
- tests/sqlmodel/crud/test_get_multi.py
- tests/sqlmodel/crud/test_get_multi_by_cursor.py
- tests/sqlmodel/crud/test_get_multi_joined.py
- tests/sqlmodel/crud/test_update.py
- Advanced filters (Django ORM style)
- Optional Bulk Operations
- Custom soft delete mechanisms in FastCRUD, EndpointCreator and crud_router
- Tests for new features
___
When initializing `crud_router` or creating a custom `EndpointCreator`, you can pass the names of your custom soft delete columns through the `FastCRUD` initialization. This informs FastCRUD which columns to check and update for soft deletion operations.
Here's an example of using `crud_router` with custom soft delete columns:
```python
from fastapi import FastAPI
from fastcrud import FastCRUD, crud_router
from sqlalchemy.ext.asyncio import AsyncSession
app = FastAPI()
my_model_crud = FastCRUD(MyModel,
is_deleted_column='archived',  # Custom 'is_deleted' column name
deleted_at_column='archived_at'  # Custom 'deleted_at' …
```
> Crud enhancement

- README.md
- docs/advanced/endpoint.md
- docs/index.md
- docs/quick-start.md
- docs/sqlmodel.md
- docs/usage/crud.md
- docs/usage/endpoint.md
In previous version all the endpoints have mandatory `local_kw` query parameter. And it was confusing..
It was solved by adding `get_session` dependency.
Also, added code what creates database tables before the app's start
This PR fixes the problem, explained in [issue 12](https://github.com/igorbenav/fastcrud/issues/12).
Added `get_session` dependency in documentation examples.
Additionally, I added code that creates database tables before the app's start. I think it's better than new users can just run example and see results without any errors
Еhese changes do not affect the library code. Only documentation
- [+] I have read the [CONTRIBUTING](CONTRIBUTING.md) document.
- [+] My code follows the code style of this project.
- [+] I have added necessary documentation (if appropriate).
- …
> Fixed an error in the documentation examples

- docs/advanced/endpoint.md
- docs/index.md
- docs/quick-start.md
- docs/sqlmodel.md
- docs/usage/endpoint.md
- fastcrud/crud/fast_crud.py
- fastcrud/endpoint/crud_router.py
- fastcrud/endpoint/endpoint_creator.py
- fastcrud/exceptions/__init__.py
- pyproject.toml
- custom updated_at column name
- passing crud to crud_router and EndpointCreator now optional
- exceptions in http_exceptions now also in exceptions module
___
```python
You can also customize your `updated_at` column:
```python hl_lines="9"
app.include_router(endpoint_creator(
session=async_session,
model=MyModel,
create_schema=CreateMyModelSchema,
update_schema=UpdateMyModelSchema,
delete_schema=DeleteMyModelSchema,
path="/mymodel",
tags=["MyModel"],
updated_at_column='date_updated'
))
```
> Passing CRUD now optional, Custom updated_at Column name

- docs/advanced/endpoint.md
- fastcrud/endpoint/crud_router.py
- fastcrud/endpoint/endpoint_creator.py
- tests/sqlalchemy/endpoint/test_endpoint_custom_names.py
- tests/sqlmodel/endpoint/test_endpoint_custom_names.py
You can customize the names of the auto generated endpoints by passing an `endpoint_names` dictionary when initializing the `EndpointCreator` or calling the `crud_router` function. This dictionary should map the CRUD operation names (`create`, `read`, `update`, `delete`, `db_delete`, `read_multi`, `read_paginated`) to your desired endpoint names.
Here's how you can customize endpoint names using the `crud_router` function:
```python
from fastapi import FastAPI
from yourapp.crud import crud_router
from yourapp.models import YourModel
from yourapp.schemas import CreateYourModelSchema, UpdateYourModelSchema
from yourapp.database import async_session
app = FastAPI()
custom_endpoint_names = {
"create": "add",
"read": "fetch",
"update": "modify",
"delete": "remove",
"read_multi": "list", …
```
> 16 is there a way to customize the path suffix added by crud router

- README.md
- docs/advanced/crud.md
- docs/usage/crud.md
- fastcrud/__init__.py
- fastcrud/crud/fast_crud.py
- fastcrud/crud/helper.py
- pyproject.toml
- tests/sqlalchemy/conftest.py
- tests/sqlalchemy/crud/test_get_joined.py
- tests/sqlalchemy/crud/test_get_multi_joined.py
- tests/sqlmodel/conftest.py
- tests/sqlmodel/crud/test_get_joined.py
- tests/sqlmodel/crud/test_get_multi_joined.py
- Now get_joined and get_multi_joined can be used with multiple models.
___
To facilitate complex data relationships, `get_joined` and `get_multi_joined` can be configured to handle joins with multiple models. This is achieved using the `joins_config` parameter, where you can specify a list of `JoinConfig` instances, each representing a distinct join configuration.
Consider a scenario where you want to retrieve users along with their associated tier and department information. Here's how you can achieve this using `get_multi_joined`.
Start by creating a list of the multiple models to be joined:
```python hl_lines="1 3-10 12-19" title="Join Configurations"
from fastcrud import JoinConfig
joins_config = [
JoinConfig(
model=Tier,
join_on=User.tier_id == Tier.id,
join_prefix="tier_", …
```
> Using `get_joined` and `get_multi_joined` for multiple models

- docs/advanced/crud.md
- docs/advanced/overview.md
- fastcrud/__init__.py
- fastcrud/crud/fast_crud.py
- fastcrud/crud/helper.py
- tests/sqlalchemy/conftest.py
- tests/sqlalchemy/crud/test_get_joined.py
- tests/sqlalchemy/crud/test_get_multi_joined.py
- tests/sqlmodel/conftest.py
- tests/sqlmodel/crud/test_get.py
- tests/sqlmodel/crud/test_get_joined.py
- tests/sqlmodel/crud/test_get_multi_by_cursor.py
- tests/sqlmodel/crud/test_get_multi_joined.py
- tests/sqlmodel/crud/test_update.py
- Now get_joined and get_multi_joined can be used with aliases, making it possible to join the same model multiple times.
___
In complex query scenarios, particularly when you need to join a table to itself or perform multiple joins on the same table for different purposes, aliasing becomes crucial. Aliasing allows you to refer to the same table in different contexts with unique identifiers, avoiding conflicts and ambiguity in your queries.
For both `get_joined` and `get_multi_joined` methods, when you need to join the same model multiple times, you can utilize the `alias` parameter within your `JoinConfig` to differentiate between the joins. This parameter expects an instance of `AliasedClass`, which can be created using the `aliased` function from SQLAlchemy (also in fastcrud for …
> Using Aliases

- docs/advanced/crud.md
- docs/advanced/overview.md
- docs/usage/crud.md
- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_select.py
- tests/sqlmodel/crud/test_select.py
This is essentially a bug fix + docs for #28 by @dubusster 
- bug fix
- docstring enhanced
- docs added both in `usage` and `advanced`
- more tests
- tests reformatted to multiple functions
In select, checking whether `sort_columns` are provided were written as follows:
```python
if "sort_columns":
stmt = self._apply_sorting(stmt, sort_columns, sort_orders)
```
Which was fixed to:
```python
if sort_columns:
stmt = self._apply_sorting(stmt, sort_columns, sort_orders)
```
> Select method changes and docs

- docs/advanced/crud.md
- docs/advanced/joins.md
- docs/advanced/overview.md
- docs/usage/crud.md
- fastcrud/crud/fast_crud.py
- fastcrud/crud/helper.py
- mkdocs.yml
- pyproject.toml
- tests/sqlalchemy/conftest.py
- tests/sqlalchemy/crud/test_count.py
- tests/sqlalchemy/crud/test_get_multi_by_cursor.py
- tests/sqlalchemy/crud/test_get_multi_joined.py
- tests/sqlalchemy/crud/test_select.py
- tests/sqlalchemy/endpoint/test_get_items.py
- tests/sqlalchemy/endpoint/test_update_item.py
- tests/sqlmodel/conftest.py
- tests/sqlmodel/crud/test_count.py
- tests/sqlmodel/crud/test_get_multi_by_cursor.py
- tests/sqlmodel/crud/test_get_multi_joined.py
- tests/sqlmodel/crud/test_select.py
- tests/sqlmodel/endpoint/test_get_items.py
- tests/sqlmodel/endpoint/test_update_item.py
- `count` method now correctly counts Many-to-Many joined models
- Support for joined models in `count` method (passing `joins_config`)
- Filters added for joined models (as `filters` in `JoinConfig`)
- Relevant tests
- Relevant docs (including for many-to-many)
___
`JoinConfig` is a detailed configuration mechanism for specifying joins between models in FastCRUD queries. It contains the following key attributes:
- **`model`**: The SQLAlchemy model to join.
- **`join_on`**: The condition defining how the join connects to other models.
- **`join_prefix`**: An optional prefix for the joined columns to avoid column name conflicts.
- **`schema_to_select`**: An optional Pydantic schema for selecting specific columns from the joined model.
- **`join_type`**: The type of join (e.g., "left", …
> Improved Joins

- fastcrud/crud/fast_crud.py
- fastcrud/endpoint/endpoint_creator.py
- fastcrud/endpoint/helper.py
- pyproject.toml
- tests/sqlalchemy/conftest.py
- tests/sqlalchemy/crud/test_create.py
- tests/sqlalchemy/endpoint/test_create_item.py
- tests/sqlalchemy/endpoint/test_get_item.py
- tests/sqlmodel/conftest.py
- tests/sqlmodel/crud/test_create.py
- tests/sqlmodel/endpoint/test_create_item.py
- tests/sqlmodel/endpoint/test_get_item.py
This PR aims to provide multiple primary key handling with the basic crud and the endpoint creator. 
This way, for a model such as :
```python
class MultiPkModel(Base):
__tablename__ = "multi_pk"
id = Column(Integer, primary_key=True)
uuid = Column(String(32), primary_key=True)
name = Column(String, unique=True)
```
the endpoint creator should gives a path like `/multi_pk/get/{id}/{uuid}` for the different endpoints (get, update and delete) that need primary keys to interact with the database. The order of path parameter is given by the column order.
There is some monkey patching of TypeDecorator to also cover custom types. 
Although it works, this piece of code seems a bit hacky and might need improvement from SQLModel or even better sqlalchemy.
Add multiple primary keys tests on create, …
> feat: ✨ add multiple primary keys support

- fastcrud/crud/fast_crud.py
Hi, I saw you fixed the optional count feature on your own. Sorry, I was a bit busy recently and had some minor issues running poetry on my WSL. New implementation looks cool, just 1 additional thing which I spotted during my development is count can be skipped in some cases entirerly.
Tests pass without changes.
> Skip count call when possible

- fastcrud/crud/fast_crud.py
This PR is a small refactor of #28, it makes use of `select` method across FastCRUD class to avoid code duplication.
`fast_crud.py` : `get`, `get_multi` and `get_multi_by_cursor`
No tests added, it passes all current ones
> refactor: :recycle: reuse of select method in FastCRUD

- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_get.py
- tests/sqlmodel/crud/test_get.py
This PR aims to add a parameter `strict` to FastCRUD `get` method. 
Indeed, when one want to retrieve some instance with some filters, and there are many results, the get method returns the first it encounters but doesn't warn the user of the other ones in the database. It can be misleading when you expect only one row in your database but there are a lot of duplicates in the table and you get no error.
So, if once needs it, it can use the `strict` parameter in get method to get one or none element.
```python
class Model(Base):
id: int = Column(Integer)
name: int = Column(String)
model1 = Model(id=1, name="Igor")
model2 = Model(id=2, name="Igor")
crud = FastCRUD(Model)
db.add(model1)
db.add(model2)
await db.commit()
await crud.get(db, id=1) # --> gives model1
await crud.get(db, id=3) # …
```
> feat: :sparkles: add strict parameter to FastCRUD `get` method

- docs/advanced/crud.md
- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/core/test_parse_filters.py
- tests/sqlmodel/core/test_parse_filters.py
This PR adds support for in_ filtering in crud methods like FastCRUD.select(item_id__in=[1,2]).
Extended parse_filters method with addtional elif op == "in", mapping to sqlalchemy/sqlmodel or() filter.
Added a test to test_parse_filters for both sqlalchemy and sqlmodel.
I was trying to acomplish something similar for or_() but it turned out to be too complex for now.
> feat: filter __in

- docs/advanced/crud.md
- docs/advanced/joins.md
- docs/usage/crud.md
- fastcrud/crud/fast_crud.py
- fastcrud/crud/helper.py
- tests/sqlalchemy/conftest.py
- tests/sqlalchemy/core/test_nest_multi_join_data.py
- tests/sqlalchemy/crud/test_get_joined.py
- tests/sqlalchemy/crud/test_get_multi_joined.py
- tests/sqlmodel/conftest.py
- tests/sqlmodel/core/test_nest_multi_join_data.py
- tests/sqlmodel/crud/test_get_joined.py
- tests/sqlmodel/crud/test_get_multi_joined.py
This fixes #91. Btw I'm not completely satisfied with the implementation, but it's enough for now.
___
FastCRUD provides flexibility in handling one-to-one and one-to-many relationships through `get_joined` and `get_multi_joined` methods, along with the ability to specify how joined data should be structured using both the `relationship_type` (default `one-to-one`) and the `nest_joins` (default `False`) parameters.
- **`get_joined`**: Fetch a single record and its directly associated record (e.g., a user and their profile).
- **`get_multi_joined`** (with `nest_joins=False`): Retrieve multiple records, each linked to a single related record from another table (e.g., users and their profiles).
Let's define two tables:
```python
class User(Base):
__tablename__ = "user"
id = Column(Integer, …
```
> One-to-many support in joins

- docs/advanced/crud.md
- docs/usage/crud.md
> [!WARNING]
> Note that naive `datetime` such as `datetime.utcnow` is not supported by `FastCRUD` as it was [deprecated](https://github.com/python/cpython/pull/103858). 
> Use timezone aware `datetime`, such as `datetime.now(UTC)` instead.
Closes #92
> warning added to docs

- docs/advanced/crud.md
- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/core/test_parse_filters.py
- tests/sqlmodel/core/test_parse_filters.py
This implements #79 by introducing `FastCRUD._get_sqlalchemy_filter()` method and a dictonary of filter mappings in `FastCRUD._SUPPORTED_FILTERS`. Adding new sqlalchemy opertors is as simple as extending the dictonary.
It also solves the `or_()` operator issue:
```
ItemCRUD.get_multi(
name__or={'startswith': 'foo', 'endswith': 'bar'}
)
```
There is some mypy issue which I struggle to solve, but it looks like it's not required. The tests pass with good coverage.
> Missing sqlalchemy operators

- docs/advanced/crud.md
- docs/advanced/endpoint.md
- fastcrud/endpoint/endpoint_creator.py
- tests/sqlalchemy/endpoint/test_endpoint_custom_names.py
This PR implements https://github.com/igorbenav/fastcrud/issues/67. It covers 2 issues:
1. It provides support for passing empty endpoint_names to fastcrud.crud_router() without redundant `//` in generated paths
```
endpoint_names = {
"create": "",
"read": "",
"update": "",
"delete": "",
"db_delete": "",
"read_multi": "",
"read_paginated": "get_paginated",
}
```
2. It mixes existing _read_paginated endpoint logic into _read_items. Now "page" and "items_per_page" query parameters can be passed to _read_paginated resulting in same behavour. I also confirmed that old-style request for _read_items persist it's functinality. Default:
```curl -X 'GET' \
'http://localhost:8000/users/get_multi?offset=0&limit=100' \
-H 'accept: application/json'
```
works for both and new _read_items.
3. …
> Simplified endpoints

- fastcrud/endpoint/endpoint_creator.py
- tests/sqlalchemy/endpoint/test_get_paginated.py
- tests/sqlmodel/endpoint/test_get_paginated.py
The new tests should completely replace the previous ones when read_paginated endpoint is deprecated
> new tests for get_items paginated, coverage at 100%

- docs/usage/crud.md
- fastcrud/crud/fast_crud.py
- fastcrud/crud/helper.py
- fastcrud/endpoint/crud_router.py
- fastcrud/endpoint/endpoint_creator.py
- fastcrud/endpoint/helper.py
- fastcrud/types.py
- tests/sqlalchemy/endpoint/test_endpoint_custom_names.py
- tests/sqlalchemy/endpoint/test_get_paginated.py
- tests/sqlmodel/endpoint/test_get_paginated.py
My changes solve #58 and allow users to directly use SQLModel without type-issues. It passes all tests and shows no typing issues.
I made many none-obtrusive type changes such as replacing instances of `type[DeclarativeBase]` with `type[Union[DeclarativeBase, SQLModel]]`. This alone caused mypy errors do to __table__ not being present on SQLModel which doesn't make sense as it does, so I think this is just poor typing on SQLModel's side. To deal with this wherever model.__title__ is being referenced I explicitly checked if that field was available and raised a ValueError if it was not. Doing this allowed my changes to pass all linting checks.
> Add type-checking support for SQLModel types.

- docs/advanced/crud.md
- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_update.py
This change allows CRUD users to retrieve the updated record after performing an `update` operation by passing `return_columns` and optionally the model to load the response into.
closes: #106
- add `return_columns` arg to the `update` function
- add `schema_to_select` arg to the `update` function
- add `return_as_model` arg to the `update` function
- add `one_or_none` arg to the `update` function
- add `Optional[Union[dict, BaseModel]]` return type as it now can return data
We use the same args that we also use in other CRUD API functions to make it easier for users to understand and use them.
I have added tests for update operations returning a single row, multiple rows, with model and without (i.e. `dict`).
> Add returning clause to update

- docs/advanced/crud.md
- docs/advanced/endpoint.md
- docs/advanced/joins.md
- docs/advanced/overview.md
- docs/index.md
- docs/installing.md
- docs/usage/crud.md
- docs/usage/endpoint.md
- docs/usage/overview.md
- fastcrud/crud/fast_crud.py
- fastcrud/crud/helper.py
- fastcrud/endpoint/crud_router.py
- fastcrud/endpoint/endpoint_creator.py
- fastcrud/paginated/helper.py
- fastcrud/paginated/response.py
Preliminary to work I've been doing for #72, this PR is to some cleanup of the docs and docstrings, mostly in terms of consistency in formatting. See the Changes section for more details.
* Add inline code markup in places where it's missing.
* Add trailing commas in example multi-line parameter lists.
* Adjust spacing and tab indent levels.
* Migrate soft delete column final paragraphs up: Put them before talking about an updated-at column instead of after, so we're not randomly going back to a previous topic.
* Quote strings in code markup to make it clear that they are strings.
* Replace some HTML in docs with Markdown. (Couldn't quite figure out how to do it for the HTML at the start of `index.md`, but still an improvement.)
* Apply correct/standard formatting to `paginated/` …
> Doc formatting cleanup

- tests/sqlalchemy/conftest.py
- tests/sqlmodel/conftest.py
Another PR based on stuff discovered while working on #72, this one changes the return type for the async session fixture, because `yield` makes the fixture function a generator.
Make the return type for the async session fixtures `AsyncGenerator[AsyncSession]` instead of just `AsyncSession`.
No tests added or changed; just fixture typing.
> Fix return type for async session fixture in tests.

- docs/advanced/crud.md
- fastcrud/crud/fast_crud.py
- pyproject.toml
- tests/sqlalchemy/conftest.py
- tests/sqlalchemy/crud/test_upsert.py
This is about enabling users to upsert multiple models/rows.
- add `upsert_multi` to `FastCRUD` using dialect-optimized sql
- add `psycopg` dependency for executing postgres statements via sqlalchemy
- add `testcontainers` to run tests in a ephemeral postgres container
closes: #110 
- add postgres-specific `upsert_multi` test
- add sqlite-specific `upsert_multi` test
- add mysql-specific `upsert_multi` test
> Add upsert_multi

- docs/advanced/crud.md
- docs/advanced/endpoint.md
- docs/index.md
- docs/quick-start.md
- docs/sqlmodel.md
- docs/usage/crud.md
- docs/usage/endpoint.md
- fastcrud/crud/fast_crud.py
- fastcrud/endpoint/crud_router.py
- fastcrud/endpoint/endpoint_creator.py
- fastcrud/examples/item/model.py
- fastcrud/examples/item/schemas.py
- fastcrud/examples/item/sqlmodel.py
- fastcrud/examples/mymodel/model.py
- fastcrud/examples/mymodel/schemas.py
- mkdocs.yml
This is the first batch of models and schemas for #72, covering the simpler, one-off models that don't have relationships. Further PRs will be batched out according to groups of related models.
* Add simple example model for `Comment`.
* Correct schema names for `OtherModel`.
Skipping defining the model/schemas this time, as nothing else uses them and it's irrelevant to just showing an additional endpoint router. I considered changing it to another more commonly used model/schema set, but decided it wasn't worth the hassle of figuring out.
* Add `pymdownx.details` to `mkdocs` config.
Used for collapsed/folded code blocks as needed for doing multiple file includes via snippets.
* Model, schemas, and doc fixes for `Item`.
This makes use of the `pymdownx.details` extension to allow for …
> Models and Schemas, Batch 1: Simple/One-Off Models

- fastcrud/crud/fast_crud.py
(Possibly?) corrected relative links from `fast_crud.py`'s docstrings to the section of the docs covering advanced filters.
This is a possible correction to #124: `mkdocs` complains about not recognizing the relative links' destination. The recommendation it provides didn't quite make sense to me relative to the URL structure as rendered, but it apparently automatically substituted it in and it appeared to work, so I just left them as I'd written them.
Now, I realize now that it may be more about the actual structure of the filesystem getting from `api/fastcrud.md` (which contains the includes from the code's docstrings) to `advanced/crud.md`, and `mkdocs` handles translating the file paths to URLs. So I put this PR together to fix the links and you can figure out whether or not it needs …
> Correct links to advanced filters in docstrings?

- docs/usage/crud.md
- fastcrud/crud/fast_crud.py
- fastcrud/endpoint/crud_router.py
- fastcrud/examples/customer/model.py
- fastcrud/examples/customer/schemas.py
- fastcrud/examples/order/model.py
- fastcrud/examples/order/schemas.py
- fastcrud/examples/product/model.py
- fastcrud/examples/product/schemas.py
This is the second batch of models and schemas for #72, covering `Customer`, `Product`, and `Order`.
Models, schemas, and doc/docstring updates for `Customer`, `Product`, and `Order`.
No changes to tests; this is purely in documentation and examples.
> Models and Schemas, Batch 2: Customers, Products, and Orders

- fastcrud/crud/fast_crud.py
Noticed `griffe` complaining about not having a type annotation for `**kwargs` in `fast_crud.py`'s `select()` while compiling docs, so putting this tiny PR together to backfill that.
Added type annotation to a `kwargs` parameter.
> kwargs missing type

- fastcrud/crud/fast_crud.py
- fastcrud/endpoint/crud_router.py
Breaking this out from #130 in an admittedly possibly unnecessary attempt to keep each of the PRs I'm doing smaller and more specifically focused on a single thing.
Adding a collapsed example space in `fast_crud.py`'s docstring, akin to what's already in `crud_router.py` from #127, for includes of models/schemas to be added into in other PRs.
> Add collapsed space for models/schemas in `fast_crud.py`

- docs/changelog.md
- docs/usage/endpoint.md
- fastcrud/crud/fast_crud.py
- fastcrud/crud/helper.py
- fastcrud/endpoint/helper.py
- pyproject.toml
- tests/sqlalchemy/conftest.py
- tests/sqlmodel/conftest.py
> Preparations for 0.14.0

- docs/advanced/crud.md
- docs/advanced/joins.md
- fastcrud/crud/fast_crud.py
- fastcrud/endpoint/crud_router.py
- fastcrud/examples/department/model.py
- fastcrud/examples/department/schemas.py
- fastcrud/examples/story/model.py
- fastcrud/examples/story/schemas.py
- fastcrud/examples/task/model.py
- fastcrud/examples/task/schemas.py
- fastcrud/examples/tier/model.py
- fastcrud/examples/tier/schemas.py
- fastcrud/examples/user/model.py
- fastcrud/examples/user/schemas.py
This is the third batch of models and schemas for #72, making up something like a simple task management system.
Models, schemas, and doc/docstring updates for:
- `Tier`
- `Department`
- `User`
- `Story` (Replacement for `Project` in this model set to reduce confusion with the `Project` that's part of the models defined in tests.)
- `Task`
One thing I want to note is that, in `docs/advanced/joins.md`, the examples between the "Getting Joined Data Nested" section and the later "One-to-One Relationships" appear to be identical? It feels unnecessarily redundant to me, but I'm not sure what to do about it. I just wanted to get it noted for the review and see if anyone else who reads this has any ideas.
> Models and Schemas, Batch 3: Task Management

- .gitignore
- fastcrud/crud/fast_crud.py
- fastcrud/endpoint/crud_router.py
- tests/sqlalchemy/core/test_parse_filters.py
- tests/sqlmodel/core/test_parse_filters.py
There is an error in the normal use of the between filter, this pr will fix it!
Fixed `_parse_filters` method
Added test cases to sqlalchemy and sqlmodel: `test_parse_filters_between_condition`.
This repair process also includes changes to .gitignore, notably there was a mypy type checking error in crud_router, which I was unable to fix, but instead skipped it over checking.
> fix complex parameter filter with between

- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_upsert.py
This is about allowing overrides to the update logic of the SQL query of the `upsert_multi` operation. This is useful if you have more custom logic to update on, such as when using `case` statements.
```python
update_override={"name": case(
(fast_crud.model.name.is_(None), stmt.excluded.name),
else_=fast_crud.model.name,
)}
```
Add `update_override` arg to `upsert_multi` and implement it for all three currently supported dialects i.e. postgresql, sqlite, and mysql.
I have added one test per dialect that validates that `update_override` is being respected and updates the value regardless of the default logic.
> Add update override arg to upsert_multi

- fastcrud/crud/fast_crud.py
This pull request introduces changes to make the is_deleted field optional and configurable in the soft delete logic of the FastCRUD class. This issues https://github.com/igorbenav/fastcrud/issues/88
Added logic to conditionally update the is_deleted column based on its presence in the configuration.
Updated the soft delete process to only set the is_deleted field if it is explicitly configured.
No new tests have been added yet
> Make `is_deleted` Field Optional and Configurable in Soft Delete Logic

- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_update.py
fixes: https://github.com/igorbenav/fastcrud/issues/168
Add the option to commit the update when `return_columns` or `return_as_model` is used.
I have added a test that manually rolls back the current transaction to see if the record was updated and committed.
> Add missing commit to update

- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_upsert.py
fixes: https://github.com/igorbenav/fastcrud/issues/170
Add a `commit` option to `upsert_multi`.
I have added an assertion to check whether we are still in a transaction after calling `upsert_multi` with `commit=True`.
> Add commit option to upsert_multi

- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_get_multi_by_cursor.py
- tests/sqlalchemy/crud/test_update.py
- tests/sqlmodel/crud/test_get_multi_by_cursor.py
- tests/sqlmodel/crud/test_update.py
Improve the behaviour of CRUD `update` method when the filtered item for update is not found.
It was requested (and closes #137) to keep consistency with the CRUD `delete` method.
Raise exception `NoResultFound` when the filters for the object to update don't match any items.
Updated:
`sqlalchemy/crud/test_update.py`: `test_update_non_existent_record`, `test_update_invalid_filters`
`sqlalchemy/crud/test_get_multi_by_cursor.py`:  `test_test_get_multi_by_cursor_pagination_integrity`
`sqlmodel/crud/test_update.py`: `test_update_non_existent_record`, `test_update_invalid_filters`
`sqlmodel/crud/test_get_multi_by_cursor.py`:  `test_test_get_multi_by_cursor_pagination_integrity`
> Improve update method when item is not found

- .github/workflows/linting.yml
- .github/workflows/python-versions.yml
- .github/workflows/tests.yml
- .github/workflows/type-check.yml
Bump outdated actions containing node16
Fixes #179 
- Bump checkout action v3 -> v4
- Bump setup-python action v4 -> v5
CI/CD run successfully and without node16 deprecation warnings after a Pull Request creation
closes #179
> Bump actions to avoid node16 EOL issue

- fastcrud/endpoint/endpoint_creator.py
- tests/sqlmodel/endpoint/test_get_paginated.py
fixes: https://github.com/igorbenav/fastcrud/issues/175
Added default values for pagination (for when filling just page_number or just items_per_page)
Added tests to validate default page or default items_per_page on get list usage.
.
> fix: default page or items_per_page for when paginating using the get on list

- fastcrud/crud/fast_crud.py
- fastcrud/crud/helper.py
- fastcrud/endpoint/crud_router.py
- fastcrud/endpoint/endpoint_creator.py
- fastcrud/types.py
- tests/sqlmodel/conftest.py
- tests/sqlmodel/endpoint/test_get_item.py
- tests/sqlmodel/endpoint/test_get_items.py
Adds an optional kwarg for the `EndpointCreator` and `crud_router` to specify a Pydantic schema for returning objects rather than dicts.
I've added documentation on the classes docstrings wrt to the new kwarg, but will need some guidance/help to add to the pages and on what to build examples.
Closes https://github.com/igorbenav/fastcrud/issues/113
- add a `select_schema` optional kwarg to `EndpointCreator` and `crud_router`
- add a `SelectSchemaType`
- replaces `BaseModel` in the `schema_to_select` arguments and appropriate returns
- add if/else logic for `FastCRUD._read_item` and `FastCRUD._read_items`
- refactor of the logic around `is_paginated` and `has_offset_limit` in `FastCRUD._read_items`
- addition of client fixture with `select_schema` set to `read_schema` fixture and tests with …
> Implement `select_schema` on `EndpointCreator` and `crud_router`

- fastcrud/endpoint/helper.py
- pyproject.toml
- tests/sqlalchemy/core/test_uuid.py
- tests/sqlmodel/core/test_uuid.py
> UUID support

- fastcrud/crud/fast_crud.py
- fastcrud/endpoint/helper.py
- fastcrud/types.py
- tests/sqlalchemy/core/test_uuid.py
- tests/sqlalchemy/crud/test_update.py
- tests/sqlmodel/core/test_uuid.py
- tests/sqlmodel/crud/test_update.py
Closes #126, #123
- Get multi with return_as_model is now properly typed
- Filter with a UUID that is not a primary key now working
- Update with not found record now raise error as previously defined by warning
> Some fixes

- docs/advanced/crud.md
- docs/advanced/joins.md
- docs/usage/crud.md
- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/conftest.py
Models and schemas for #72, using the models from the unit tests for projects, project participants, and the associations between the two.
Doc snippet inclusion markers in unit test config for models:
* `Project`
* `Participant`
* `ProjectsParticipantsAssociation`
Also, addition of a `ReadProjectSchema` and doc/docstring updates overall for all of these.
As noted above, `tests/sqlalchemy/conftest.py` has snippet markers added for the above models, but are otherwise functionally unchanged.
Coming back to this after a while away. I made sure to rebase and otherwise tried to ensure that changes that have happened in the meantime aren't affected, but please let me know if I've missed something.
> Models and Schemas, Batch 5: Projects and Participants

- pyproject.toml
"pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 42.0.0-44.0.0 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://openssl-library.org/news/secadv/20250211.txt."
> bump cryptography to fix vulnerability

- fastcrud/endpoint/endpoint_creator.py
- tests/sqlalchemy/conftest.py
- tests/sqlalchemy/crud/test_get_multi.py
- tests/sqlmodel/conftest.py
- tests/sqlmodel/endpoint/test_get_items.py
Adds a new pytest fixture that creates a test client with predefined filter configurations (tier_id, name, name__startswith) to test filtered endpoints
I've added changes like author mentioned in https://github.com/igorbenav/fastcrud/issues/196
Endpoint Creator now has extended logic in _validate_filter_config, but it waits for developer to add filters in FilterConfig, or like Simon did in generate_filter_configs.
I've added test case to filter by startwith name, 1 positive case, 1 negative case.
- [x ] I have read the [CONTRIBUTING](CONTRIBUTING.md) document.
- [x ] My code follows the code style of this project.
- [x ] I have added tests that cover my changes (if applicable).
- [x ] All new and existing tests passed.
Include any additional information that you think is important for …
> Implement advanced filter configs

- docs/advanced/filters.md
- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_get_multi.py
refactor: improve FastCRUD filter parsing readability and operations
- Split _parse_filters into smaller, focused helper methods
- Added proper type hints and docstrings for better clarity
- Fixed variable shadowing in column handling
- Improved error handling consistency
- Added dedicated methods for:
- _handle_simple_filter
- _handle_or_filter
- _handle_not_filter
- _handle_standard_filter
- _get_column
Implementation Notes:
- OR operations: field__or={'gt': 18, 'lt': 65} applies multiple conditions to same field Example: age__or={'gt': 18, 'lt': 65} -> WHERE age > 18 OR age < 65
- NOT operations: field__not={'eq': value, 'between': (x,y)} applies NOT to each condition
Example: age__not={'eq': 20, 'between': (30,40)} ->
WHERE NOT age = 20 AND NOT (age BETWEEN 30 AND 40)
Makes the code …
> Implement OR and NOT for filtering.

- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_get_multi_joined_total_count.py
Issue Summary
The issue was in the get_multi_joined method of the FastCRUD class. When using the join_model parameter without providing joins_config, the method was incorrectly passing only joins_config to the count method instead of the combined join_definitions list. This resulted in incorrect total_count values when using join_model.
Solution
I fixed the issue by changing line 2128 in fastcrud/crud/fast_crud.py to pass join_definitions instead of joins_config to the count method:
Solving: https://github.com/igorbenav/fastcrud/issues/219
I created a new test file tests/sqlalchemy/crud/test_get_multi_joined_total_count.py with two test cases:
test_get_multi_joined_total_count_with_join_model - Tests that total_count is correct when using join_model …
> Fix get_multi_joined total_count with join_model parameter.

- pyproject.toml
in this version they have fixed python_type issue which is raised when using sqlalchemy_utils types with fastcrud
update dependency version
fix this issue https://github.com/benavlabs/crudadmin/issues/21
> fix: update sqlalchemy-utils dependency version to 0.41.2

- docs/advanced/endpoint.md
- fastcrud/endpoint/endpoint_creator.py
- tests/sqlalchemy/endpoint/test_delete_item.py
- tests/sqlalchemy/endpoint/test_update_item.py
- tests/sqlmodel/endpoint/test_delete_item.py
- tests/sqlmodel/endpoint/test_update_item.py
Problem
Endpoints generated via crud_router for Update and Delete returned 500 Internal Server Error when the target record ID did not exist, due to sqlalchemy.exc.NoResultFound bubbling up from the CRUD layer.
Solution
- Translate NoResultFound into NotFoundException (HTTP 404) at the endpoint layer for update and delete operations.
- This mirrors the existing behavior already present in the read (GET) single-item endpoint.
Implementation Details
- fastcrud/endpoint/endpoint_creator.py
- _update_item: wrap self.crud.update(...) in try/except the NoResultFound and raise NotFoundException(detail="Item not found").
- _delete_item: wrap self.crud.delete(...) in try/except the NoResultFound and raise NotFoundException(detail="Item not found").
- docs/advanced/endpoint.md
- Documented that …
> Return 404 on non-existent IDs for update/delete endpoints (Fixes #253)

- docs/advanced/filters.md
- fastcrud/crud/fast_crud.py
- tests/sqlalchemy/crud/test_get_multi.py
- tests/sqlalchemy/crud/test_multiple_like_or.py
- tests/sqlmodel/crud/test_get_multi.py
- tests/sqlmodel/crud/test_multiple_like_or.py
This PR adds support for using multiple values with the same operator in `__or` and `__not` filters. This allows more flexible filtering patterns, particularly useful for matching multiple LIKE patterns on the same field.
- Enhanced `_handle_or_filter` method to accept lists of values for operators
- Enhanced `_handle_not_filter` method to accept lists of values for operators  
- Fixed existing tests that had duplicate dictionary keys (invalid Python syntax)
- Added comprehensive test coverage for the new feature
- Updated documentation with examples of the new syntax
Related to filtering enhancement requests for more flexible OR conditions.
- Added `tests/sqlalchemy/crud/test_multiple_like_or.py` with 6 test cases covering:
- Multiple LIKE patterns with OR
- Multiple values with NOT …
> Support Multiple Values for Same Operator in OR/NOT Filters
