README.md, docs/usage/crud.md, fastcrud/crud/fast_crud.py, fastcrud/endpoint/crud_router.py, fastcrud/endpoint/endpoint_creator.py
- Type hints fixes
- Changed a couple of things in docs
- Added dynamic descriptions in auto generated endpoints
=> type hints fix, also changed in docs, descriptions in endpoints

docs/index.md
add necessary package import for doc
doc
not need 
=> fix: add necessary package import

.github/workflows/type-check.yml, fastcrud/crud/fast_crud.py, fastcrud/crud/helper.py, fastcrud/endpoint/crud_router.py, fastcrud/endpoint/endpoint_creator.py, fastcrud/endpoint/helper.py, pyproject.toml
Typing errors fixed, mypy workflow added
=> Type checking

pyproject.toml
=> version in pyproject bumped

docs/usage/crud.md, fastcrud/crud/fast_crud.py, fastcrud/endpoint/helper.py, tests/sqlalchemy/crud/test_update.py, tests/sqlalchemy/endpoint/test_custom_route.py, tests/sqlmodel/crud/test_update.py, tests/sqlmodel/endpoint/test_custom_route.py
=> Optional count

docs/advanced/joins.md, docs/changelog.md, docs/usage/crud.md, fastcrud/crud/fast_crud.py, fastcrud/crud/helper.py, pyproject.toml, tests/sqlalchemy/crud/test_get_joined.py, tests/sqlalchemy/crud/test_get_multi_joined.py, tests/sqlmodel/crud/test_get_joined.py, tests/sqlmodel/crud/test_get_multi_joined.py
=> Nested responses

docs/advanced/joins.md, fastcrud/crud/fast_crud.py, fastcrud/crud/helper.py, fastcrud/endpoint/helper.py, mypy.ini, tests/sqlalchemy/crud/test_get_joined.py, tests/sqlalchemy/crud/test_get_multi_joined.py, tests/sqlmodel/crud/test_get_joined.py, tests/sqlmodel/crud/test_get_multi_joined.py
Not done, but this will fix #64, #65 and #66
=> Join fixes

fastcrud/endpoint/crud_router.py, fastcrud/endpoint/endpoint_creator.py, fastcrud/endpoint/helper.py, tests/sqlalchemy/conftest.py
=> Dependencies

fastcrud/crud/fast_crud.py, tests/sqlalchemy/conftest.py, tests/sqlmodel/conftest.py
=> Skip commit

docs/advanced/crud.md, fastcrud/crud/fast_crud.py
=> Docstring fix

docs/advanced/crud.md, docs/changelog.md, docs/usage/crud.md
=> Updated docs

docs/changelog.md, fastcrud/crud/fast_crud.py, fastcrud/endpoint/helper.py, pyproject.toml, tests/sqlalchemy/core/test_parse_filters.py, tests/sqlmodel/core/test_parse_filters.py
=> deprecation warning added to depends

fastcrud/crud/fast_crud.py, fastcrud/crud/helper.py, tests/sqlalchemy/conftest.py, tests/sqlalchemy/core/test_parse_filters.py, tests/sqlalchemy/crud/test_get_joined.py, tests/sqlalchemy/crud/test_get_multi_joined.py, tests/sqlmodel/conftest.py, tests/sqlmodel/core/test_parse_filters.py, tests/sqlmodel/crud/test_get_joined.py, tests/sqlmodel/crud/test_get_multi_joined.py
=> null primary key bug fixed

docs/changelog.md, pyproject.toml
=> changelog and pyproject

fastcrud/crud/fast_crud.py, fastcrud/endpoint/crud_router.py, fastcrud/endpoint/endpoint_creator.py
These are some tweaks to spacing and naming that I apparently missed while doing #127. Trying to combo-pack it with other changes I'm doing was proving confusing, so I'm making it its own thing.
Add some vertical whitespace and fix some object names in docstrings.
=> Backfill docstring fixes.

tests/sqlalchemy/conftest.py
This change will make sure tests don't fail if docker is not installed
cc @slaarti 
addresses: https://github.com/igorbenav/fastcrud/issues/110#issuecomment-2241901618
=> Add docker client check before running tests that require docker

docs/advanced/joins.md, fastcrud/crud/fast_crud.py, fastcrud/crud/helper.py, fastcrud/examples/article/model.py, fastcrud/examples/article/schemas.py, fastcrud/examples/author/model.py, fastcrud/examples/author/schemas.py, fastcrud/examples/profile/model.py, fastcrud/examples/profile/schemas.py
Models and schemas for #72, making up something like a content management system. I'd missed this one during my initial survey for the original issue, but it became apparent as I was working on #140.
Models, schemas, and doc/docstring updates for:
* `Profile`
* `Author` (Renamed from "`User`" in this model set to disambiguate from the one used in the task management model set.)
* `Article` (Renamed from/unified with "`Post`"; I went with "article" because it sounded fancier to go with "author". 😁)
=> Models and Schemas, Batch 4: Articles, Authors, and Profiles

fastcrud/crud/fast_crud.py
=> Fix update column

docs/quick-start.md
Fix Quick-Start documentation.
- Add missing imports
- Call `get_session` instead of `session` in the `crud_router`
N/A
=> chore: fix quick-start documentation

fastcrud/crud/helper.py, tests/sqlalchemy/conftest.py, tests/sqlalchemy/core/test_parse_filters.py, tests/sqlalchemy/endpoint/test_get_paginated.py, tests/sqlmodel/conftest.py, tests/sqlmodel/core/test_parse_filters.py, tests/sqlmodel/endpoint/test_get_paginated.py
=> Custom name bug fix

fastcrud/crud/fast_crud.py, fastcrud/endpoint/endpoint_creator.py, fastcrud/types.py
=> response model in swagger

fastcrud/endpoint/endpoint_creator.py
Please provide a clear and concise description of what your pull request is about.
Briefly list the changes you've made. If applicable, also link any relevant issues or pull requests.
Describe the tests you added or modified to cover your changes, if applicable.
=> fix: ‌remove redundant code

fastcrud/crud/fast_crud.py
Reduced branching in _as_single_response, _as_multi_response. delete method has cleaner logic for soft delete.
Briefly list the changes you've made. If applicable, also link any relevant issues or pull requests.
Describe the tests you added or modified to cover your changes, if applicable.
=> code optimizations in fast_crud.py

README.md
add warning about non-native column types in SQLAlchemy models
=> docs: add warning about non-native column types in SQLAlchemy models
